"""Module defining builtin macros for use in code generation templates."""

from __future__ import annotations  # Until Python 3.14

from collections.abc import Callable
from dataclasses import dataclass, field
from functools import cached_property
from typing import Any, TypeAlias

from smal.schemas.state_machine import SMALFile

SMALMacroContextComputeFn: TypeAlias = Callable[[SMALFile], Any]


@dataclass(frozen=True)
class SMALMacro:
    """Data class representing a macro that can be used in code generation templates."""

    name: str
    filename: str
    lang: str
    description: str
    params: list[str]
    extra_context: dict[str, Any] = field(default_factory=dict)
    computed_extra_context: dict[str, SMALMacroContextComputeFn] = field(default_factory=dict)

    @cached_property
    def import_path(self) -> str:
        """Get the package import path for this macro.

        Returns:
            str: The import path for this macro, which can be used to load the macro's template file.

        """
        return f"macros/{self.filename}"

    @cached_property
    def signature(self) -> str:
        """Get the call signature of this macro.

        Returns:
            str: The call signature of this macro, which is the macro name followed by its parameters in parentheses.

        """
        if self.params:
            return f"{self.name}({', '.join(self.params)})"
        return f"{self.name}()"


class MacroRegistry:
    """Namespace class for managing SMAL code generation macros."""

    _macros: dict[str, SMALMacro] | None = None

    @classmethod
    def _get_macros(cls) -> dict[str, SMALMacro]:
        if cls._macros is None:
            cls._macros = {
                "c_autogen_banner": SMALMacro(
                    name="c_autogen_banner",
                    filename="c_autogen_banner.j2",
                    lang="c",
                    description="Macro that creates a C-style file banner disclosing that the file was autogenerated by SMAL.",
                    params=["smal"],
                ),
                "c_autogen_banner_state_machine": SMALMacro(
                    name="c_autogen_banner_state_machine",
                    filename="c_autogen_banner_state_machine.j2",
                    lang="c",
                    description="Macro that creates a C-style file banner disclosing that the file was autogenerated by SMAL for a specific state machine.",
                    params=["smal"],
                ),
                "c_machine_constants": SMALMacro(
                    name="c_machine_constants",
                    filename="c_machine_constants.j2",
                    lang="c",
                    description="Macro that generates all defined constants from a .smal file in C as #defines.",
                    params=["smal"],
                ),
                "c_machine_errors": SMALMacro(
                    name="c_machine_errors",
                    filename="c_machine_errors.j2",
                    lang="c",
                    description="Macro that generates the enumeration of all defined errors from a .smal file in C.",
                    params=["smal"],
                ),
                "c_machine_events": SMALMacro(
                    name="c_machine_events",
                    filename="c_machine_events.j2",
                    lang="c",
                    description="Macro that generates the enumeration of all defined events from a .smal file in C.",
                    params=["smal"],
                ),
                "c_machine_state_table_entry": SMALMacro(
                    name="c_machine_state_table_entry",
                    filename="c_machine_state_table_entry.j2",
                    lang="c",
                    description="Macro that generates the C struct representing a state table entry/transition for the machine defined in a .smal file.",
                    params=["smal", "max_actions"],
                ),
                "c_machine_states": SMALMacro(
                    name="c_machine_states",
                    filename="c_machine_states.j2",
                    lang="c",
                    description="Macro that generates the enumeration of all defined states/substates from a .smal file in C.",
                    params=["smal"],
                ),
                "c_machine_struct": SMALMacro(
                    name="c_machine_struct",
                    filename="c_machine_struct.j2",
                    lang="c",
                    description="Macro that generates the struct representing the state machine from a .smal file in C.",
                    params=["smal"],
                ),
                "c_machine_version": SMALMacro(
                    name="c_machine_version",
                    filename="c_machine_version.j2",
                    lang="c",
                    description="Macro that generates a C #define defining the version of the state machine from a .smal file.",
                    params=["smal"],
                ),
                "c_state_transition_table": SMALMacro(
                    name="c_state_transition_table",
                    filename="c_state_transition_table.j2",
                    lang="c",
                    description="Macro that generates the entire state transition table from a .smal file in C.",
                    params=["smal"],
                ),
            }
        return cls._macros

    def __new__(cls) -> None:
        """Create a new instance of the MacroRegistry.

        Raises:
            NotImplementedError: MacroRegistry is a namespace class and cannot be instantiated.

        """
        raise NotImplementedError("MacroRegistry is a namespace class and cannot be instantiated.")

    @classmethod
    def get(cls, name: str) -> SMALMacro:
        """Get a SMAL macro by name.

        Args:
            name (str): The name of the macro to retrieve.

        Raises:
            ValueError: If the macro with the given name does not exist.

        Returns:
            SMALMacro: The SMAL macro with the given name.

        """
        macros = cls._get_macros()
        if name not in macros:
            raise ValueError(f"Unknown macro: {name}")
        return macros[name]

    @classmethod
    def list_macros(cls) -> list[SMALMacro]:
        """List all builtin SMAL macros.

        Returns:
            list[SMALMacro]: The list of all builtin SMAL macros.

        """
        return list(cls._get_macros().values())

    @classmethod
    def list_macro_names(cls) -> list[str]:
        """List all builtin SMAL macro names.

        Returns:
            list[str]: The list of all builtin SMAL macro names.

        """
        return list(cls._get_macros().keys())

    @classmethod
    def has_macro(cls, name: str) -> bool:
        """Get whether or not a macro with the given name exists.

        Args:
            name (str): The name of the macro to check for.

        Returns:
            bool: True if a macro with the given name exists, False otherwise.

        """
        return name in cls._get_macros()
