from __future__ import annotations  # Until Python 3.14

from collections.abc import Callable
from dataclasses import dataclass, field
from functools import cached_property
from typing import Any, TypeAlias

from smal.schemas.state_machine import SMALFile

SMALMacroContextComputeFn: TypeAlias = Callable[[SMALFile], Any]


@dataclass(frozen=True)
class SMALMacro:
    name: str
    filename: str
    lang: str
    description: str
    params: list[str]
    extra_context: dict[str, Any] = field(default_factory=dict)
    computed_extra_context: dict[str, SMALMacroContextComputeFn] = field(default_factory=dict)

    @cached_property
    def import_path(self) -> str:
        return f"macros/{self.filename}"

    @cached_property
    def signature(self) -> str:
        if self.params:
            return f"{self.name}({', '.join(self.params)})"
        return f"{self.name}()"


class MacroRegistry:
    _macros = {
        "c_autogen_banner": SMALMacro(
            name="c_autogen_banner",
            filename="c_autogen_banner.j2",
            lang="c",
            description="Macro that creates a C-style file banner disclosing that the file was autogenerated by SMAL.",
            params=["smal"],
        ),
        "c_machine_constants": SMALMacro(
            name="c_machine_constants",
            filename="c_machine_constants.j2",
            lang="c",
            description="Macro that generates all defined constants from a .smal file in C as #defines.",
            params=["smal"],
        ),
        "c_machine_errors": SMALMacro(
            name="c_machine_errors",
            filename="c_machine_errors.j2",
            lang="c",
            description="Macro that generates the enumeration of all defined errors from a .smal file in C.",
            params=["smal"],
        ),
        "c_machine_events": SMALMacro(
            name="c_machine_events",
            filename="c_machine_events.j2",
            lang="c",
            description="Macro that generates the enumeration of all defined events from a .smal file in C.",
            params=["smal"],
        ),
        "c_machine_state_table_entry": SMALMacro(
            name="c_machine_state_table_entry",
            filename="c_machine_state_table_entry.j2",
            lang="c",
            description="Macro that generates the C struct representing a state table entry/transition for the machine defined in a .smal file.",
            params=["smal", "max_actions"],
        ),
        "c_machine_states": SMALMacro(
            name="c_machine_states",
            filename="c_machine_states.j2",
            lang="c",
            description="Macro that generates the enumeration of all defined states/substates from a .smal file in C.",
            params=["smal"],
        ),
        "c_machine_struct": SMALMacro(
            name="c_machine_struct",
            filename="c_machine_struct.j2",
            lang="c",
            description="Macro that generates the struct representing the state machine from a .smal file in C.",
            params=["smal"],
        ),
        "c_machine_version": SMALMacro(
            name="c_machine_version",
            filename="c_machine_version.j2",
            lang="c",
            description="Macro that generates a C #define defining the version of the state machine from a .smal file.",
            params=["smal"],
        ),
        "c_state_transition_table": SMALMacro(
            name="c_state_transition_table",
            filename="c_state_transition_table.j2",
            lang="c",
            description="Macro that generates the entire state transition table from a .smal file in C.",
            params=["smal"],
        ),
    }

    def __new__(cls) -> None:
        raise NotImplementedError("MacroRegistry is a namespace class and cannot be instantiated.")

    @classmethod
    def get(cls, name: str) -> SMALMacro:
        if name not in cls._macros:
            raise ValueError(f"Unknown macro: {name}")
        return cls._macros[name]

    @classmethod
    def list_macros(cls) -> list[SMALMacro]:
        return list(cls._macros.values())

    @classmethod
    def list_macro_names(cls) -> list[str]:
        return list(cls._macros.keys())

    @classmethod
    def has_macro(cls, name: str) -> bool:
        return name in cls._macros
