#ifndef EXAMPLE_H
#define EXAMPLE_H

#include <stdint.h>

#define EXAMPLE_VERSION 1.0.0

// CONSTANTS
#define EXAMPLE_CONSTANT_A 5
#define EXAMPLE_CONSTANT_B 10
#define EXAMPLE_CONSTANT_C 15

// STATES
typedef enum _example_state_t {
    EXAMPLE_STATE_IDLE = 0,
    EXAMPLE_STATE_MEASURING = 1,
    EXAMPLE_STATE_APPLYING_FILTERS = 2,
} example_state_t;

// EVENTS
typedef enum _example_event_t {
    EXAMPLE_EVENT_START_MEASUREMENT = 0,
    EXAMPLE_EVENT_MEASUREMENT_SUCCEEDED = 1,
    EXAMPLE_EVENT_MEASUREMENT_FAILED = 2,
    EXAMPLE_EVENT_APPLY_FILTERS = 3,
    EXAMPLE_EVENT_FILTERS_APPLIED = 4,
} example_event_t;

// COMMANDS
// TBD

// MESSAGES
// TBD

// ENUMS
//TBD

// STRUCTS
//TBD

#endif // EXAMPLE_H