name: Release (TestPyPI)

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write  # REQUIRED for Trusted Publishing

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install python-semantic-release==9.21.1 build

      - name: Run semantic-release (TestPyPI)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEMANTIC_RELEASE_PYPI_REPOSITORY: "https://test.pypi.org/legacy/"
        run: semantic-release publish
