name: Continuous Delivery

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      dist_artifacts_name: dist  # artifact name
      dist_artifacts_dir: dist   # folder where Python packages will live
      lock_file_artifact: uv.lock
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          fetch-tags: true

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install Python & Project dependencies
        run: uv sync --all-extras --dev

      - name: Build Python distributions
        run: uv build --out-dir dist

      - name: Detect next version
        id: version
        env:
          GH_TOKEN: "none"
        run: uv run semantic-release -v version --no-changelog --no-commit --no-tag

      - name: Upload Distribution Artifacts
        if: ${{ steps.version.outputs.released == 'true' }}
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.dist_artifacts_name }}  # MUST match the download step later
          path: ${{ env.dist_artifacts_dir }}/**
          if-no-files-found: error
          retention-days: 2

  release:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.new-release-detected == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Build artifacts again (optional but ensures they exist)
        run: uv build

      - name: Create and publish release
        id: release
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          uv run semantic-release -v --strict version
          uv run semantic-release publish

  deploy:
    name: Deploy to PyPI
    runs-on: ubuntu-latest
    needs:
      - build
      - release
    if: ${{ needs.release.outputs.released == 'true' }}
    environment:
      name: pypi
      url: https://pypi.org/project/smal-lang/
    permissions:
      id-token: write
    steps:
      - name: Download Distribution Artifacts
        uses: actions/download-artifact@v6
        with:
          name: ${{ needs.build.outputs.distribution-artifacts }}  # MUST match build upload
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          print-hash: true
          verbose: true